--connect db2.sample;
--drop table word;
--drop table userRole;
--drop table users;
--commit;
set userid=db2admin;
set passwd=db2admin;
connect db2.sample;
commit;
drop table word;
commit;
create table word  (
    id bigint
      NOT NULL GENERATED BY DEFAULT AS IDENTITY (
      START WITH +1
      INCREMENT BY +1
      MINVALUE +1
      MAXVALUE +2147483647
      NO CYCLE
      CACHE 20
      NO ORDER ) ,
    value varchar(150) not null,
    points int not null,
    primary key (id)
);
insert into word (value, points) values ('simple',   20);
insert into word (value, points) values ('compound', 30);
insert into word (value, points) values ('password', 50);
insert into word (value, points) values ('notwithstanding', 90);
commit;
select * from word;
commit;

  drop table userRole;
  drop table Users;

commit;

CREATE TABLE Users (
  id bigint
      NOT NULL GENERATED BY DEFAULT AS IDENTITY (
      START WITH +1
      INCREMENT BY +1
      MINVALUE +1
      MAXVALUE +2147483647
      NO CYCLE
      CACHE 20
      NO ORDER ) ,
  Name VARCHAR(50)  UNIQUE NOT NULL, /*  needed to ensure case sensitive. */
  Password VARCHAR(50)  NOT NULL,  /*  needed to ensure case sensitive. Must hash the password. */
  Language VARCHAR(25) NOT NULL DEFAULT 'en',
  FormSourceId VARCHAR(100) ,         /* Defends against CSRF attacks. */
  PRIMARY KEY (Id)
) ;

CREATE TABLE UserRole (
  Name VARCHAR(50)  NOT NULL,
  Role VARCHAR(50)  NOT NULL,
  FOREIGN KEY (Name) REFERENCES Users(Name),
  PRIMARY KEY (Name, Role)
) ;

-- Populate tables with some base data.
-- *** WARNING *** : this data is for development only, and must be DELETED from production environments.
-- The passwords are in hashed form, and have the cleartext value 'testtest'.
INSERT INTO Users (Id, Name, Password) VALUES(1, 'testeA', '51abb9636078defbf888d8457a7c76f85c8f114c');
INSERT INTO Users (Id, Name, Password) VALUES(2, 'testeB', '51abb9636078defbf888d8457a7c76f85c8f114c');
INSERT INTO Users (Id, Name, Password) VALUES(3, 'testeC', '51abb9636078defbf888d8457a7c76f85c8f114c');
INSERT INTO Users (Id, Name, Password) VALUES(4, 'testeD', '51abb9636078defbf888d8457a7c76f85c8f114c');
INSERT INTO Users (Id, Name, Password) VALUES(5, 'richard','51abb9636078defbf888d8457a7c76f85c8f114c');

INSERT INTO UserRole (Name, Role) VALUES('testeA', 'user-general');
INSERT INTO UserRole (Name, Role) VALUES('testeB', 'translator');
INSERT INTO UserRole (Name, Role) VALUES('testeC', 'webmaster');
INSERT INTO UserRole (Name, Role) VALUES('testeD', 'user-general');
INSERT INTO UserRole (Name, Role) VALUES('testeD', 'translator');
INSERT INTO UserRole (Name, Role) VALUES('testeD', 'webmaster');
INSERT INTO UserRole (Name, Role) VALUES('testeD', 'user-president');
INSERT INTO UserRole (Name, Role) VALUES('testeD', 'access-control');
INSERT INTO UserRole (Name, Role) VALUES('richard','user-general');
INSERT INTO UserRole (Name, Role) VALUES('richard','translator');
INSERT INTO UserRole (Name, Role) VALUES('richard','webmaster');
INSERT INTO UserRole (Name, Role) VALUES('richard','admin');
INSERT INTO UserRole (Name, Role) VALUES('richard','user');
commit;
select * from users;
select * from userRole;
commit;
